SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG_SCORE,2) AS SCORE
FROM REST_INFO AS RI
INNER JOIN(
    SELECT AVG(REVIEW_SCORE) AS AVG_SCORE, REVIEW_TEXT,REVIEW_DATE, REST_ID
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS RR
ON RI.REST_ID = RR.REST_ID 
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, RI.FAVORITES DESC;